development:
  adapter: postgresql
  encoding: utf8
  database: sam_thornton_development
  pool: 16
  timeout: 5000

test: &test
  adapter: postgresql
  encoding: utf8
  host: localhost
  database: sam_thornton_test<%= ENV['TEST_DB_ID'] %><%= ENV['TEST_ENV_NUMBER'] %>
  pool: 16
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: sam_thornton
  pool: 16
  timeout: 5000

cucumber:
  <<: *test
